[tool.ruff]
line-length = 100
target-version = "py311"

[tool.ruff.lint]
select = [
    "E",
    "W",
    "F",
    "I",
    "B",
    "C4",
    "UP",
]
ignore = [
    "E501",
    "B008",
    "C901",
]

[tool.ruff.lint.isort]
known-first-party = ["rag_engine"]

[tool.pytest.ini_options]
testpaths = ["rag_engine/tests"]
python_files = "test_*.py"
python_functions = "test_*"


